// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An image-based plant problem diagnosis AI agent.
 *
 * - diagnosePlantFromImage - A function that handles the plant diagnosis process from an image.
 * - DiagnosePlantFromImageInput - The input type for the diagnosePlantFromImage function.
 * - DiagnosePlantFromImageOutput - The return type for the diagnosePlantFromImage function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const DiagnosePlantFromImageInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of a plant, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type DiagnosePlantFromImageInput = z.infer<typeof DiagnosePlantFromImageInputSchema>;

const MedicationSchema = z.object({
    name: z.string().describe('Tên của thuốc hoặc phương pháp.'),
    reason: z.string().describe('Giải thích ngắn gọn tại sao thuốc này được đề xuất (ví dụ: "ức chế sự phát triển của nấm", "tăng cường sức đề kháng cho cây").')
});

const TreatmentRecommendationSchema = z.object({
    suggestedMedications: z.array(MedicationSchema).describe('Danh sách các loại thuốc hoặc phương pháp được đề xuất, cùng với lý do ngắn gọn.'),
    applicationInstructions: z.string().describe('Hướng dẫn chi tiết cách áp dụng các loại thuốc/phương pháp.'),
});

const DiagnosePlantFromImageOutputSchema = z.object({
  plantIdentification: z.string().describe("Tên của loại cây được xác định từ hình ảnh."),
  diagnosis: z.string().describe('Chẩn đoán bệnh của cây từ hình ảnh.'),
  severityScore: z.number().min(0).max(100).describe('Điểm mức độ nghiêm trọng của bệnh, từ 0 (rất nhẹ) đến 100 (rất nặng).'),
  explanation: z.string().describe("Giải thích chi tiết về lý do đưa ra chẩn đoán, dựa trên các dấu hiệu nhìn thấy trong ảnh."),
  treatment: z.object({
    biological: TreatmentRecommendationSchema.describe('Đề xuất điều trị bằng phương pháp sinh học.'),
    chemical: TreatmentRecommendationSchema.describe('Đề xuất điều trị bằng phương pháp hóa học.'),
  }),
  similarDiseases: z.array(z.object({
    name: z.string().describe('Tên của bệnh tương tự.'),
    imageHint: z.string().describe('Gợi ý từ khóa gồm hai từ cho hình ảnh của bệnh tương tự, ví dụ: "leaf blight".')
  })).describe('Danh sách các bệnh trông tương tự để so sánh trực quan.')
});
export type DiagnosePlantFromImageOutput = z.infer<typeof DiagnosePlantFromImageOutputSchema>;

export async function diagnosePlantFromImage(input: DiagnosePlantFromImageInput): Promise<DiagnosePlantFromImageOutput> {
  return diagnosePlantFromImageFlow(input);
}

const prompt = ai.definePrompt({
  name: 'diagnosePlantFromImagePrompt',
  input: {schema: DiagnosePlantFromImageInputSchema},
  output: {schema: DiagnosePlantFromImageOutputSchema},
  prompt: `Bạn là một chuyên gia thực vật học chuyên nhận dạng cây và chẩn đoán các bệnh của cây trồng dựa trên hình ảnh.

Nhiệm vụ của bạn là:
1. Xác định loại cây trong hình ảnh.
2. Chẩn đoán bệnh hoặc vấn đề mà cây đang gặp phải.
3. Đánh giá mức độ nghiêm trọng của bệnh trên thang điểm từ 0 (hoàn toàn không có dấu hiệu bệnh) đến 100 (cây gần như đã chết) và cung cấp nó trong trường 'severityScore'.
4. Cung cấp một giải thích rõ ràng và chi tiết về lý do bạn đưa ra chẩn đoán đó, dựa trên các dấu hiệu thị giác từ hình ảnh (ví dụ: "Tôi chẩn đoán là bệnh X vì tôi thấy các đốm màu Y trên lá, phù hợp với triệu chứng của bệnh này").
5. Cung cấp một kế hoạch điều trị **TOÀN DIỆN**. Kế hoạch này phải bao gồm **CẢ HAI** phương pháp điều trị 'Sinh học' và 'Hóa học'. Ưu tiên các giải pháp sinh học nếu có thể. Đối với mỗi phương pháp, hãy cung cấp danh sách các loại thuốc/sản phẩm cụ thể và hướng dẫn sử dụng chi tiết. **Với mỗi loại thuốc, hãy cung cấp một lý do ngắn gọn cho việc đề xuất nó (trường 'reason').**
6. Cung cấp một danh sách 2-3 bệnh khác có triệu chứng hình ảnh tương tự để người dùng có thể so sánh. Đối với mỗi bệnh tương tự, hãy cung cấp một gợi ý hình ảnh ngắn gọn (2 từ).

**QUAN TRỌNG: Toàn bộ phản hồi của bạn PHẢI được viết bằng tiếng Việt.**

Hình ảnh cây trồng: {{media url=photoDataUri}}
`,
});

const diagnosePlantFromImageFlow = ai.defineFlow(
  {
    name: 'diagnosePlantFromImageFlow',
    inputSchema: DiagnosePlantFromImageInputSchema,
    outputSchema: DiagnosePlantFromImageOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
