// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A medication recommendation AI agent.
 *
 * - recommendMedication - A function that handles the medication recommendation process.
 * - RecommendMedicationInput - The input type for the recommendMedication function.
 * - RecommendMedicationOutput - The return type for the recommendMedication function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RecommendMedicationInputSchema = z.object({
  diagnosis: z.string().describe('Chẩn đoán bệnh cây trồng.'),
  plantType: z.string().describe('Loại cây bị ảnh hưởng.'),
});
export type RecommendMedicationInput = z.infer<typeof RecommendMedicationInputSchema>;

const RecommendMedicationOutputSchema = z.object({
  medicationName: z.string().describe('Tên thuốc được đề nghị.'),
  usageInstructions: z.string().describe('Hướng dẫn sử dụng thuốc.'),
  dosage: z.string().describe('Liều lượng thuốc được đề nghị.'),
});
export type RecommendMedicationOutput = z.infer<typeof RecommendMedicationOutputSchema>;

export async function recommendMedication(input: RecommendMedicationInput): Promise<RecommendMedicationOutput> {
  return recommendMedicationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'recommendMedicationPrompt',
  input: {schema: RecommendMedicationInputSchema},
  output: {schema: RecommendMedicationOutputSchema},
  prompt: `Bạn là một chuyên gia về bệnh cây và thuốc chữa bệnh.

  Dựa trên chẩn đoán và loại cây được cung cấp, hãy đề nghị một loại thuốc phù hợp, cung cấp hướng dẫn sử dụng và chỉ định liều lượng.

  Chẩn đoán: {{{diagnosis}}}
  Loại cây: {{{plantType}}}

  Vui lòng cung cấp tên thuốc, hướng dẫn sử dụng và liều lượng một cách rõ ràng và ngắn gọn.
  `,
});

const recommendMedicationFlow = ai.defineFlow(
  {
    name: 'recommendMedicationFlow',
    inputSchema: RecommendMedicationInputSchema,
    outputSchema: RecommendMedicationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
