// This is an autogenerated file from Firebase Studio.

export type Pest = {
    name: string;
    description: string;
    prevention: string[];
    affectedCrops: string[];
    riskLevel: 'cao' | 'trung bình' | 'thấp';
};

export type PestForecastData = {
    month: number;
    monthName: string;
    forecasts: Pest[];
};

export type ProvinceForecast = {
    provinceName: string;
    monthlyForecasts: PestForecastData[];
}

export const allPestForecasts: ProvinceForecast[] = [
    {
        provinceName: "Đồng bằng sông Cửu Long",
        monthlyForecasts: [
            {
                month: 7,
                monthName: 'Tháng Bảy',
                forecasts: [
                    {
                        name: 'Bệnh đạo ôn (cháy lá) trên lúa',
                        description: 'Thời tiết nóng ẩm mưa nhiều là điều kiện lý tưởng cho bệnh đạo ôn phát triển mạnh, đặc biệt trên các giống lúa nhiễm.',
                        prevention: [
                            'Sử dụng giống kháng bệnh.',
                            'Bón phân NPK cân đối, tránh bón thừa đạm.',
                            'Thăm đồng thường xuyên để phát hiện bệnh sớm.',
                            'Phun thuốc đặc trị khi thấy vết bệnh đầu tiên xuất hiện.'
                        ],
                        affectedCrops: ['Lúa'],
                        riskLevel: 'cao',
                    },
                     {
                        name: 'Sâu cuốn lá nhỏ hại lúa',
                        description: 'Sâu non ăn biểu bì lá, làm giảm khả năng quang hợp của cây, ảnh hưởng đến năng suất.',
                        prevention: [
                            'Bảo vệ thiên địch như ong ký sinh, bọ rùa.',
                            'Dọn sạch cỏ dại ven bờ.',
                            'Phun thuốc sinh học khi mật độ sâu cao.'
                        ],
                        affectedCrops: ['Lúa'],
                        riskLevel: 'trung bình',
                    }
                ],
            },
            {
                month: 8,
                monthName: 'Tháng Tám',
                forecasts: [
                    {
                        name: 'Rầy nâu hại lúa',
                        description: 'Cuối mùa mưa, rầy nâu có thể bùng phát thành dịch, truyền bệnh vàng lùn, lùn xoắn lá, gây hại nghiêm trọng.',
                        prevention: [
                            'Sử dụng giống kháng rầy.',
                            'Xuống giống đồng loạt, tập trung để né rầy.',
                            'Theo dõi mật độ rầy bằng bẫy đèn và kiểm tra gốc lúa.',
                            'Chỉ phun thuốc khi mật độ rầy cao và có sự tư vấn của cán bộ kỹ thuật.',
                        ],
                        affectedCrops: ['Lúa'],
                        riskLevel: 'cao',
                    },
                ],
            },
            {
                month: 9,
                monthName: 'Tháng Chín',
                forecasts: [
                    {
                        name: 'Bệnh lem lép hạt trên lúa',
                        description: 'Do nhiều loại nấm gây ra, phát triển mạnh khi lúa trổ trong điều kiện mưa nhiều, độ ẩm cao. Làm hạt lúa bị đen, lửng, lép.',
                        prevention: [
                            'Không gieo sạ quá dày.',
                            'Bón phân cân đối, không bón thừa đạm muộn.',
                            'Phun phòng bằng các loại thuốc đặc trị nấm trước và sau khi lúa trổ.'
                        ],
                        affectedCrops: ['Lúa'],
                        riskLevel: 'trung bình',
                    },
                ],
            },
        ]
    },
    {
        provinceName: "Tây Nguyên",
        monthlyForecasts: [
             {
                month: 7,
                monthName: 'Tháng Bảy',
                forecasts: [
                    {
                        name: 'Bệnh gỉ sắt trên cà phê',
                        description: 'Bệnh phát triển mạnh trong mùa mưa, gây rụng lá hàng loạt, làm giảm khả năng quang hợp và năng suất.',
                        prevention: [
                            'Tỉa cành, tạo hình thông thoáng.',
                            'Bón phân đầy đủ, cân đối để cây khỏe.',
                            'Phun thuốc gốc đồng hoặc thuốc đặc trị vào đầu mùa mưa.'
                        ],
                        affectedCrops: ['Cà phê'],
                        riskLevel: 'cao',
                    },
                ],
            },
            {
                month: 8,
                monthName: 'Tháng Tám',
                forecasts: [
                     {
                        name: 'Bệnh nứt thân xì mủ trên cây sầu riêng',
                        description: 'Bệnh do nấm Phytophthora gây ra, thường phát triển mạnh sau các đợt mưa kéo dài, làm thối rễ, nứt thân, chảy nhựa.',
                        prevention: [
                            'Làm đất cao, tạo hệ thống thoát nước tốt.',
                            'Quét vôi vào gốc cây vào đầu mùa mưa.',
                            'Hạn chế gây vết thương ở vùng gốc và rễ.',
                            'Sử dụng các loại thuốc gốc Metalaxyl, Mancozeb hoặc Phosphonate để tưới hoặc quét lên vết bệnh.',
                        ],
                        affectedCrops: ['Sầu riêng'],
                        riskLevel: 'trung bình',
                    },
                ],
            },
            {
                month: 9,
                monthName: 'Tháng Chín',
                forecasts: [
                    {
                        name: 'Tuyến trùng rễ trên hồ tiêu',
                        description: 'Tuyến trùng gây hại bộ rễ, tạo thành các khối u, làm cây còi cọc, vàng lá, sinh trưởng kém và có thể chết.',
                        prevention: [
                            'Sử dụng giống sạch bệnh.',
                            'Luân canh với cây trồng không phải là ký chủ của tuyến trùng.',
                            'Bón phân hữu cơ hoai mục, đặc biệt là phân có chứa nấm đối kháng Trichoderma.',
                            'Tưới các loại thuốc đặc trị tuyến trùng vào đầu và giữa mùa mưa.'
                        ],
                        affectedCrops: ['Hồ tiêu'],
                        riskLevel: 'thấp',
                    },
                ],
            },
        ]
    },
    {
        provinceName: "Đông Nam Bộ",
        monthlyForecasts: [
             {
                month: 7,
                monthName: 'Tháng Bảy',
                forecasts: [
                    {
                        name: 'Bệnh loét sẹo trên cây có múi',
                        description: 'Bệnh do vi khuẩn gây ra, lây lan mạnh qua mưa gió, côn trùng. Gây ra các vết loét trên lá, cành và quả.',
                        prevention: [
                            'Trồng cây chắn gió xung quanh vườn.',
                            'Cắt tỉa, tiêu hủy các bộ phận bị bệnh.',
                            'Phun thuốc gốc đồng hoặc kháng sinh khi bệnh mới xuất hiện.'
                        ],
                        affectedCrops: ['Cam', 'Chanh', 'Bưởi'],
                        riskLevel: 'trung bình',
                    },
                ],
            },
            {
                month: 8,
                monthName: 'Tháng Tám',
                forecasts: [
                     {
                        name: 'Sâu đục thân trên ngô (bắp)',
                        description: 'Sâu non đục vào thân và bắp, gây hại nặng, làm giảm năng suất và chất lượng hạt.',
                        prevention: [
                            'Luân canh cây trồng.',
                            'Vệ sinh đồng ruộng, tiêu hủy tàn dư cây trồng vụ trước.',
                            'Sử dụng bẫy pheromone để theo dõi và bắt sâu trưởng thành.',
                        ],
                        affectedCrops: ['Ngô'],
                        riskLevel: 'thấp',
                    },
                ],
            },
            {
                month: 9,
                monthName: 'Tháng Chín',
                forecasts: [
                   {
                        name: 'Bệnh thán thư trên xoài, nhãn',
                        description: 'Bệnh gây hại trên lá, hoa và quả, đặc biệt trong điều kiện độ ẩm cao, làm rụng hoa và quả non.',
                        prevention: [
                            'Cắt tỉa, tiêu hủy cành lá, quả bị bệnh.',
                            'Bao quả sớm để hạn chế nấm bệnh xâm nhập.',
                            'Phun thuốc gốc đồng hoặc các loại thuốc đặc trị thán thư trước và sau khi cây ra hoa.'
                        ],
                        affectedCrops: ['Xoài', 'Nhãn'],
                        riskLevel: 'cao',
                    },
                ],
            },
        ]
    }
];
